GET http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Make Project"
}

###
DELETE http://localhost:3001/todo/delete/6268a54ac4ff7fde381b4929

###
PUT http://localhost:3001/todo/complete/62688f2c180ab3ffb418592c